---
title: "final-project"
format: pdf
---

```{r}
library(dplyr)
library(infer)
library(moderndive)
library(tidyverse)
```

```{r}
coffee_data <- read.csv("https://wjhopper.github.io/SDS-201/data/coffee_ratings.csv")
```

```{r}
glimpse(coffee_data)
```
# Name?

## Introduction

Coffee is a beloved drink all over the world. From late night diners to upscale cafes, coffee beverages are a staple in many cultures. Along with a wide range of 
```{r}
coffee_data |>
  ggplot(data = coffee_data, mapping = aes(x= country_of_origin)) +
  geom_bar() +
  coord_flip()
```



          Hello
